language: cpp

# For Linux builds:
dist: trusty
sudo: required

# Build matrix:
matrix:
    include:
        - os: linux
          compiler: gcc
        - os: linux
          compiler: clang
          env: CFG_CC=clang CFG_CXX='clang++ -std=gnu++1z' ## -stdlib=libc++'
        - os: osx
          osx_image: xcode8
          env: CFG_CC=clang CFG_CXX='clang++ -std=gnu++1z' ##-stdlib=libc++'
#        - os: osx
#          osx_image: xcode7.3
#        - os: osx
#          osx_image: xcode7.2
#        - os: osx
#          osx_image: xcode7.2
#        - os: osx
#          osx_image: xcode7
        - os: osx
          osx_image: xcode6.4
          env: CFG_CC=clang CFG_CXX='clang++ -std=gnu++1z -stdlib=libc++'

before_install:
 - if [ $TRAVIS_OS_NAME == osx ]; then brew update; fi
 # Travis CI has a broken libtool/sed issue in the OSX image(s) <see e.g. https://github.com/libgd/libgd/issues/266#issuecomment-234697932>.
 # This is the recommended work-around until they fix it.
 - if [ $TRAVIS_OS_NAME == osx ]; then brew uninstall libtool && brew install libtool; fi
 - if [ $TRAVIS_OS_NAME == osx ]; then brew install pcre pcre2 argp-standalone the_silver_searcher; fi
 # Install gnu grep to test against. @todo Make things work so this can be installed only after a successful build.
 - if [ $TRAVIS_OS_NAME == osx ]; then brew tap homebrew/dupes; brew install grep; fi
 - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq; fi
 - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -qq libpcre3-dev && sudo apt-get install -qq silversearcher-ag; fi

before_script:
 - echo "g++ --version:" && g++ --version && autoreconf --version && automake --version && echo "===="
 - # pwd ==> /home/travis/build/gvansickle/ucg
 - #sysctl -a
 - #if [ $TRAVIS_OS_NAME == osx ]; then sysctl -a hw; fi
 - #if [ $TRAVIS_OS_NAME == linux ]; then cat /proc/cpuinfo | grep flags; fi
 - # lscpu = Doesn't exist on OSX or Cygwin
 - # free -ht = Doesn't exist on OSX or Cygwin
 - # df main.cpp # df does exist on Cygwin.  Also on OSX, but params are different, no --output, -T is different.
 - #mount | fgrep -w "`df . | grep '%' | sed -e 's/.*% *//'`"
 - git fetch --unshallow  # Travis limits its pull by default to 50 revs.  The build then can't do a proper "git describe".

script:
 - #if [ $TRAVIS_OS_NAME == osx ]; then find /usr -type d ! -perm -g+r,u+r,o+r -prune -o -type f -iname 'libpcre*.dylib' -exec ls -lF \{\} \; && echo -n "brew --prefix pcre=" && brew --prefix pcre && brew --help; fi 
 - #if [ $TRAVIS_OS_NAME == osx ]; then ls -l -R $(brew --prefix pcre); fi
 - pkg-config --list-all | grep argp || true
 - find /usr -iname '*argp*' || true
 - pkg-config --list-all | grep pcre
 - pkg-config libpcre --print-variables
 - pkg-config libpcre --print-provides
 - # Actual build starts here.
 - autoreconf -i
 - mkdir build
 - cd build
 - echo "CFG_CC=$CFG_CC CFG_CXX=$CFG_CXX"
 - ../configure CC="$CFG_CC" CXX="$CFG_CXX"
 - make
 - make check 'TESTSUITEFLAGS=--keywords=!benchmark,!characterize'
 - find . -iname '*.log' -exec cat "{}" \; 
 - echo "====" && echo "build_info.cpp:" && cat build_info.cpp && echo "===="

after_success:
 - cd ../../ && wget http://downloads.sourceforge.net/project/boost/boost/1.58.0/boost_1_58_0.tar.bz2
 - tar xjf boost_1_58_0.tar.bz2
 - cd ucg/build
 - make check #TESTSUITEFLAGS='-v -d -x'
 - cat tests/testsuite.log
 - cat tests/perf_test_results.txt
 - if [ $TRAVIS_OS_NAME == osx ]; then otool -L ucg && otool -l ucg; fi
 - if [ $TRAVIS_OS_NAME == linux ]; then LD_DEBUG=all && ldd -v ucg; fi
 - #find . -iname '*.log' -exec cat "{}" \; 
