language: cpp
sudo: required
dist: trusty

os:
 - osx
 - linux

before_install:
 - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install pcre argp-standalone; fi
 - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq && sudo apt-get install -qq libpcre3-dev; fi

before_script:
 - echo "g++ --version:" && g++ --version && echo "====" 

script:
 - autoreconf -i
 - mkdir build
 - cd build
 - ../configure --with-pcre=/usr/local/Cellar/pcre/8.38/
 - if [ $TRAVIS_OS_NAME == osx ]; then find /usr/local/Cellar -iname '*pcre*'; fi
 - make check
 - echo "build_info.cpp:" && cat build_info.cpp && echo "===="

