language: cpp
sudo: required
dist: trusty

os:
 - osx
 - linux
 
compiler:
  - clang
  - gcc

before_install:
 - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install pcre argp-standalone; fi
 - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq && sudo apt-get install -qq libpcre3-dev; fi

before_script:
 - echo "g++ --version:" && g++ --version && echo "===="
 - pwd
 - #mkdir src && cd src && wget http://downloads.sourceforge.net/project/boost/boost/1.61.0/boost_1_61_0.tar.bz2
 - #mv boost_1_61_0.tar.bz2 ~/src && tar xjf boost_1_61_0.tar.bz2

script:
 - if [ $TRAVIS_OS_NAME == osx ]; then IS_OSX=1; fi
 - if [ $TRAVIS_OS_NAME == linux ]; then IS_LINUX=1; fi
 - if [ $TRAVIS_OS_NAME == osx ]; then find /usr -type d ! -perm -g+r,u+r,o+r -prune -o -type f -iname 'libpcre*.dylib' -exec ls -lF \{\} \; && echo -n "brew --prefix pcre=" && brew --prefix pcre && brew --help; fi 
 - if [ $TRAVIS_OS_NAME == osx ]; then ls -l -R $(brew --prefix pcre); fi
 - pkg-config libpcre --print-variables
 - autoreconf -i
 - mkdir build
 - cd build
 - ../configure
 - make
 - make check #TESTSUITEFLAGS='-v -d -x'
 - ./ucg --cpp 'endif' ..
 - ./ucg --cpp 'endif' ../
 - if [ $TRAVIS_OS_NAME == osx ]; then otool -L ucg && otool -l ucg; fi
 - if [ $TRAVIS_OS_NAME == linux ]; then LD_DEBUG=all && ldd -v ucg; fi
 - echo "====" && echo "build_info.cpp:" && cat build_info.cpp && echo "===="
 - find . -iname '*.log' -exec cat "{}" \; 

