language: cpp
sudo: required
dist: trusty

os:
 - osx
 - linux
 
compiler:
  - clang
  - gcc

before_install:
 - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install pcre argp-standalone the_silver_searcher; fi
 - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq && sudo apt-get install -qq libpcre3-dev && sudo apt-get install -qq silversearcher-ag; fi

before_script:
 - echo "g++ --version:" && g++ --version && echo "===="
 - # pwd ==> /home/travis/build/gvansickle/ucg
 - sysctl -a
 - #if [ $TRAVIS_OS_NAME == osx ]; then sysctl -a hw; fi
 - if [ $TRAVIS_OS_NAME == linux ]; then cat /proc/cpuinfo | grep flags; fi
 - # lscpu = Doesn't exist on OSX or Cygwin
 - # free -ht = Doesn't exist on OSX or Cygwin
 - # df main.cpp # df does exist on Cygwin.  Also on OSX, but params are different, no --output, -T is different.
 - mount | fgrep -w "`df . | grep '%' | sed -e 's/.*% *//'`"

script:
 - if [ $TRAVIS_OS_NAME == osx ]; then IS_OSX=1; fi
 - if [ $TRAVIS_OS_NAME == linux ]; then IS_LINUX=1; fi
 - #if [ $TRAVIS_OS_NAME == osx ]; then find /usr -type d ! -perm -g+r,u+r,o+r -prune -o -type f -iname 'libpcre*.dylib' -exec ls -lF \{\} \; && echo -n "brew --prefix pcre=" && brew --prefix pcre && brew --help; fi 
 - #if [ $TRAVIS_OS_NAME == osx ]; then ls -l -R $(brew --prefix pcre); fi
 - pkg-config --list-all | grep pcre
 - pkg-config libpcre --print-variables
 - pkg-config libpcre --print-provides
 - autoreconf -i
 - mkdir build
 - cd build
 - ../configure
 - make
 - make check 'TESTSUITEFLAGS=--keywords=!performance,!characterize'
 - find . -iname '*.log' -exec cat "{}" \; 
 - echo "====" && echo "build_info.cpp:" && cat build_info.cpp && echo "===="

after_success:
 - if [ $TRAVIS_OS_NAME == osx ]; then brew tap homebrew/dupes; brew install grep; fi  # Install gnu grep to test against.
 - cd ../../ && wget http://downloads.sourceforge.net/project/boost/boost/1.58.0/boost_1_58_0.tar.bz2
 - tar xjf boost_1_58_0.tar.bz2
 - cd ucg/build
 - make check #TESTSUITEFLAGS='-v -d -x'
 - cat tests/testsuite.log
 - cat tests/perf_test_results.txt
 - if [ $TRAVIS_OS_NAME == osx ]; then otool -L ucg && otool -l ucg; fi
 - if [ $TRAVIS_OS_NAME == linux ]; then LD_DEBUG=all && ldd -v ucg; fi
 - #find . -iname '*.log' -exec cat "{}" \; 
