sudo: false

language: cpp

os:
 - osx
 - linux

install:
 - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install pcre argp-standalone; fi
 - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq && sudo apt-get install -qq pcre argp; fi

script:
 - autoreconf -i
 - mkdir build
 - cd build
 - ../configure
 - make check

 