language: cpp
sudo: required
dist: trusty

#branches:
#  only:
#    - features/OSX  # Let's only test the OSX branch for now.

os:
 - osx
 - linux
 
compiler:
  - clang
  - gcc

before_install:
 - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install pcre argp-standalone; fi
 - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq && sudo apt-get install -qq libpcre3-dev; fi

before_script:
 - echo "g++ --version:" && g++ --version && echo "====" 

script:
 - if [ $TRAVIS_OS_NAME == osx ]; then IS_OSX=1; fi
 - if [ $TRAVIS_OS_NAME == linux ]; then IS_LINUX=1; fi
 - test $IS_OSX && find /usr -type d ! -perm -g+r,u+r,o+r -prune -o -type f -iname 'libpcre*.dylib' -exec ls -lF \{\} \; && echo -n "brew --prefix pcre=" && brew --prefix pcre && brew --help 
 - test $IS_OSX && ls -l -R $(brew --prefix pcre)
 - pkg-config libpcre --print-variables
 - autoreconf -i
 - mkdir build
 - cd build
 - ../configure
 - make
 - make check #TESTSUITEFLAGS='-v -d -x'
 - ./ucg --cpp 'endif' ..
 - test $IS_OSX && otool -L ucg && otool -l ucg && otool -l ucg | grep -A 3 LC_RPATH | grep path
 - test $IS_LINUX && LD_DEBUG=all && ldd -v ucg
 - echo "====\nbuild_info.cpp:" && cat build_info.cpp && echo "===="
 - find . -iname '*.log' -exec cat "{}" \; 

